server:
  port: 9103

# DataSource Config
spring:
  datasource:
    url: jdbc:p6spy:mysql://192.168.60.16:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.60.16:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
