spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.60.16:8848

server:
  port: 8080

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    port: 20881
    id: dubbo
    name: dubbo
  scan:
    base-packages: com.example.service.impl
  registry:
    address: nacos://192.168.60.16:8848