server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.16:8848 #配置Nacos地址,注册中心
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 192.168.60.16:8081 #配置sentinel dashboard地址
        port: 8719
      #sentinel读取nacos配置中心
      datasource:
        ds:
          nacos:
            server-addr: 192.168.60.16:8848
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true