server:
  port: 8401
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.60.16:8081 #配置sentinel dashboard地址
        port: 8719
      #sentinel读取nacos配置中心
      datasource:
        ds:
          nacos:
            server-addr: 192.168.60.16:8848
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true